/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoCategoriaRouteImport } from './routes/catalogo.$categoria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoCategoriaRoute = CatalogoCategoriaRouteImport.update({
  id: '/catalogo/$categoria',
  path: '/catalogo/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo/$categoria': typeof CatalogoCategoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo/$categoria': typeof CatalogoCategoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo/$categoria': typeof CatalogoCategoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalogo/$categoria'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalogo/$categoria'
  id: '__root__' | '/' | '/catalogo/$categoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoCategoriaRoute: typeof CatalogoCategoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$categoria': {
      id: '/catalogo/$categoria'
      path: '/catalogo/$categoria'
      fullPath: '/catalogo/$categoria'
      preLoaderRoute: typeof CatalogoCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoCategoriaRoute: CatalogoCategoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
